spring:
  application:
    name: smart_delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_delivery
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080